spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
#    hibernate:
#      ddl-auto: create-drop

    show-sql: true

  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
    default-schema: public

security:
  secret-key: ${SECRET_KEY}
